### ISSUE TITLE
[bug] min-width in center is computed incorrectly

### ISSUE THREAD

**Issue by allenwoot** [foundation/foundation-emails#185]
I ran into this issue. To repro this, change the container width sass variable to 600, and use center.

For the css class `center`, min-width is set to `$width`, but it should be set to `$width - 2*$gutter_size` (unless it's collapsed)

**Comment by moteey** [comment]
Also declaration for `th` seems to be missing, causing `th` columns with nested `center` tag to always be 580px wide.

**_grids.scss: line 110**
`@for $i from 1 through $grid-column-count {
  td.large-#{$i} center {
    min-width: -zf-grid-calc-px($i, $grid-column-count, $container-width);
  }
}`

**Comment by kball** [comment]
I've fixed the th issue from @moteey in https://github.com/zurb/foundation-emails/commit/33e6c0b94d9343e106f5d8c142d30376059dfe15

I'm not seeing the issue from @allenwoot so I'm not sure if that was already addressed or I'm just missing something.  @tdhartwick @gakimball do you know?  Alternatively, @allenwoot can you try with the v2.0 branch and see if you're still seeing the issue?  Please note that `.center` class has been updated to `.text-center` for consistency with foundation-sites.

**Comment by allenwoot** [comment]
@kball I got the latest code from the v2.0 branch, and am still seeing the issue. Seems like the problem is that `min-width` for `center` and `th.large-N center` are not calculated correctly.

Repro steps
1 Change `$global-width` to 600px
2 Compile CSS
3 Render the following HTML:

```
<html><head>
    </head><body>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <table class="body">
      <tbody><tr>
        <td class="center" align="center" valign="top">
          <center>
              <table class="container">
              <tbody><tr>
                <td>
                  <table class="row ">
  <tbody><tr class="">
    <th class="columns first last small-12 large-12 ">
        <center>
        <p class="text-center">
          Sample text
        </p>
        </center>
    </th>
  </tr>
</tbody></table>
                </td>
              </tr>
            </tbody></table>
          </center>
        </td>
      </tr>
    </tbody></table>
</body></html>
```

The container will turn out to be 616px instead of 600px. They key here is the CSS for <center>, which is set as 

```
center {
  width: 100%;
  min-width: 600px; }
```

The container renders as expected when I change the CSS to the following:

```
center {
  width: 100%;
  min-width: 568px; }

td.large-12 center,
th.large-12 center {
  min-width: 568px; }
```

Let me know if I can provide more info!

**Comment by kball** [comment]
Fixed in https://github.com/zurb/foundation-emails/commit/e0b3601db75dec8c7e277aab5e94a47f91c1a9b8
